# coding: utf-8


PT = "labour, and in a great measure he has succeeded so far. But to attribute other duties to him would be unreasonable. For example, to expect that he should use this superior yield of labour in the interest of society as a whole, would be to ask philanthropy and charity of him, and a capitalist enterprise cannot be based on charity. It now remains for society, first, to extend this greater productivity, which is limited to certain industries, and to apply it to the general good. But it is evident that to utilize this high productivity of labour, so as to guarantee wellbeing to all, Society must itself take possession of all means of production. Economists, as is their wont, will not fail to remind us of the comparative wellbeing of a certain category of young robust workmen, skilled in certain special branches of industry which has been obtained under the present system. It is always this minority that is pointed out to us with pride. But even this wellbeing, which is the exclusive right of a few, is it secure? Tomorrow, maybe, negligence, improvidence, or the greed of their employers, will deprive these privileged men of their work, and they will pay for the period of comfort they have enjoyed with months and years of poverty or destitution. How many important industries—the textiles, iron, sugar, etc.without mentioning all sorts of shortlived trades, have we not seen decline or come to a standstill on account of speculations, or in consequence of natural displacement of work, or from the effects of competition amongst the capitalists themselves! If the chief textile and mechanical industries had to pass through such a crisis as they have passed through in 1886, we hardly need mention the small trades, all of which have their periods of standstill."

PT2 = "aosetuha,.uaoh.esar,ch4.spracodheuircha,o.tnspdhaorlecuidaoresudarsuhceirasoehirsahcoeicrsgaroeucraohrsucaosetuha,.uaoh.esar,ch4.spracodheuircha,o.tnspdhaorlecuidaoresudarsuhceirasoehirsahcoeicrsgaroeucraohrsucaosetuha,.uaoh.esar,ch4.spracodheuircha,o.tnspdhaorlecuidaoresudarsuhceirasoehirsahcoeicrsgaroeucraohrsucaosetuha,.uaoh.esar,ch4.spracodheuircha,o.tnspdhaorlecuidaoresudarsuhceirasoehirsahcoeicrsgaroeucraohrsucaosetuha,.uaoh.esar,ch4.spracodheuircha,o.tnspdhaorlecuidaoresudarsuhceirasoehirsahcoeicrsgaroeucraohrsucaosetuha,.uaoh.esar,ch4.spracodheuircha,o.tnspdhaorlecuidaoresudarsuhceirasoehirsahcoeicrsgaroeucraohrsucaosetuha,.uaoh.esar,ch4.spracodheuircha,o.tnspdhaorlecuidaoresudarsuhceirasoehirsahcoeicrsgaroeucraohrsucaosetuha,.uaoh.esar,ch4.spracodheuircha,o.tnspdhaorlecuidaoresudarsuhceirasoehirsahcoeicrsgaroeucraohrsucaosetuha,.uaoh.esar,ch4.spracodheuircha,o.tnspdhaorlecuidaoresudarsuhceirasoehirsahcoeicrsgaroeucraohrsucaosetuha,.uaoh.esar,ch4.spracodheuircha,o.tnspdhaorlecuidaoresudarsuhceirasoehirsahcoeicrsgaroeucraohrsucaosetuha,.uaoh.esar,ch4.spracodheuircha,o.tnspdhaorlecuidaoresudarsuhceirasoehirsahcoeicrsgaroeucraohrsucaosetuha,.uaoh.esar,ch4.spracodheuircha,o.tnspdhaorlecuidaoresudarsuhceirasoehirsahcoeicrsgaroeucraohrsucaosetuha,.uaoh.esar,ch4.spracodheuircha,o.tnspdhaorlecuidaoresudarsuhceirasoehirsahcoeicrsgaroeucraohrsucaosetuha,.uaoh.esar,ch4.spracodheuircha,o.tnspdhaorlecuidaoresudarsuhceirasoehirsahcoeicrsgaroeucraohrsucaosetuha,.uaoh.esar,ch4.spracodheuircha,o.tnspdhaorlecuidaoresudarsuhceirasoehirsahcoeicrsgaroeucraohrsucaosetuha,.uaoh.esar,ch4.spracodheuircha,o.tnspdhaorlecuidaoresudarsuhceirasoehirsahcoeicrsgaroeucraohrsucaosetuha,.uaoh.esar,ch4.spracodheuircha,o.tnspdhaorlecuidaoresudarsuhceirasoehirsahcoeicrsgaroeucraohrsucaosetuha,.uaoh.esar,ch4.spracodheuircha,o.tnspdhaorlecuidaoresudarsuhceirasoehirsahcoeicrsgaroeucraohrsucaosetuha,.uaoh.esar,ch4.spracodheuircha,o.tnspdhaorlecuidaoresudarsuhceirasoehirsahcoeicrsgaroeucraohrsucaosetuha,.uaoh.esar,ch4.spracodheuircha,o.tnspdhaorlecuidaoresudarsuhceirasoehirsahcoeicrsgaroeucraohrsucaosetuha,.uaoh.esar,ch4.spracodheuircha,o.tnspdhaorlecuidaoresudarsuhceirasoehirsahcoeicrsgaroeucraohrsuc"

PT3 = "I love the mountains I love the rolling hills I love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hillsI love the mountains I love the rolling hills"

rap = "Burning 'em, if you ain't quick and nimble\nI go crazy when I hear a cymbal"

TEST = 'this is a test'

WOKKA = 'wokka wokka!!!'

YS = "YELLOW SUBMARINE"
